[versions]
androidDesugarJdkLibs = "2.1.4"
agp = "8.10.1"
kotlin = "2.2.0"
coreKtx = "1.16.0"
junit-version = "5.8.1"
juinit-platform-suite-version = "1.8.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.9.2"
activityCompose = "1.10.1"
composeBom = "2024.09.00"
appcompat = "1.7.1"
material = "1.12.0"
firebase = "4.4.3"
firebase-bom = "34.0.0"
jetbrainsKotlinJvm = "2.0.21"
navigationUiKtx = "2.8.7"
hilt-version = "2.56.2"
hilt-nav-version = "1.2.0"
ksp-version = "2.2.0-2.0.2"
room = "2.7.2"
retrofit = "2.11.0"
retrofit2KotlinxSerializationConverter = "1.0.0"
coil3 = "3.2.0"
firebase-auth-play-services = "21.4.0"
firebase-base-play-services = "18.5.0"
kotlinx-coroutines = "1.10.2"
lottie-animation-version = "6.6.6"
aws-sdk-version = "2.81.0"
aws-sdk-service-version = "1.12.791"
kotlinx-serialization-json-version = "1.8.0"

# For build-logic
androidGradlePlugin = "8.9.0"
androidTools = "31.9.0"
firebasePerfPlugin = "2.0.1"
firebaseCrashlyticsPlugin = "3.0.6"



[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
juinit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit-version" }
juinit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-version" }
juinit-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit-version" }
juinit-platform-suite = { group = "org.junit.platform", name = "junit-platform-suite", version.ref = "juinit-platform-suite-version" }

androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationUiKtx" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json-version" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analitycs = { group = "com.google.firebase", name = "firebase-analytics"}
firebase-auth = { group = "com.google.firebase", name = "firebase-auth"}
firebase-auth-play-services  = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "firebase-auth-play-services"}
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore" }
firebase-base-play-services = { group = "com.google.android.gms", name = "play-services-base", version.ref = "firebase-base-play-services"}

hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt-version"}
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt-version" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt-version" }
hilt-compose-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-nav-version"}


retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationConverter" }
retrofit-gson-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit"}

coil3-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil3" }
coil3-network = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil3" }

androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room"}
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room"}
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room"}

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
lottie-animation = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie-animation-version"}

aws-sdk = { module = "com.amazonaws:aws-android-sdk-s3", version.ref = "aws-sdk-version"}

# Преобразует современный байт-код Java в формат, совместимый со старыми средами выполнения Android.
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }




# Gradle build libraries

# Основной плагин Android Gradle Plugin (AGP)
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
# Библиотека с общими инструментами Android Gradle Plugin
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
# Плагин компилятора Jetpack Compose для Kotlin
compose-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
# Gradle-плагин Firebase Crashlytics.
firebase-crashlytics-gradlePlugin = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsPlugin" }
# Интеграция Firebase Performance Monitoring в Android-приложение
firebase-performance-gradlePlugin = { group = "com.google.firebase", name = "perf-plugin", version.ref = "firebasePerfPlugin" }
# Добавляет поддержку Kotlin в проект
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
# Kotlin Symbol Processing (KSP) плагин.
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp-version" }
# Gradle-плагин для Room Database
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }





[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
firebase = { id = "com.google.gms.google-services", version.ref = "firebase"}
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }

kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-version" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-version" }

room = { id = "androidx.room", version.ref = "room"}

# Кастомные плагины, определенные для проекта
meatvice-android-application = { id = "meatvice.android.application" }
meatvice-android-application-compose = { id = "meatvice.android.application.compose"}

meatvice-android-library-compose = { id = "meatvice.android.library.compose"}
meatvice-android-library = { id = "meatvice.android.library" }

meatvice-hilt = { id = "meatvice.hilt"}

meatvice-android-feature = { id = "meatvice.android.feature"}

meatvice-firebase = { id = "meatvice.firebase"}
