
runAndroidLintCoreData:
  stage: lint
  script:
    - ./gradlew core:data:lint -x assembleDebug -x build
  artifacts:
    paths:
      - core/data/build/reports/lint-results-debug.html
    expire_in: 10 days
    when: always
  cache:
    key: "$CI_PROJECT_NAME"
    paths:
      - .gradle/
      - build/
      - build-logic/.gradle/
      - core/**/build/
      - app/**/build/
      - feature/**/build/
      - sdk/
    policy: pull


runAndroidLintCoreDomain:
  stage: lint
  script:
    - ./gradlew core:domain:lint -x assembleDebug -x build
  artifacts:
    paths:
      - "core/domain/build/reports/lint-results-debug.html"
    expire_in: 10 days
    when: always
  cache:
    key: "$CI_PROJECT_NAME"
    paths:
      - .gradle/
      - build/
      - build-logic/.gradle/
      - core/**/build/
      - app/**/build/
      - feature/**/build/
      - sdk/
    policy: pull

runAndroidLintDesignSystem:
  stage: lint
  script:
    - ./gradlew core:designsystem:lint -x assembleDebug -x build
  artifacts:
    paths:
      - "core/designsystem/build/reports/lint-results-debug.html"
    expire_in: 10 days
    when: always
  cache:
    key: "$CI_PROJECT_NAME"
    paths:
      - .gradle/
      - build/
      - build-logic/.gradle/
      - core/**/build/
      - app/**/build/
      - feature/**/build/
      - sdk/
    policy: pull



runAndroidLintFeatureAuth:
  stage: lint
  script:
    - ./gradlew feature:auth:lint -x assembleDebug -x build
  artifacts:
    paths:
      - "feature/auth/build/reports/lint-results-debug.html"
    expire_in: 10 days
    when: always
  cache:
    key: "$CI_PROJECT_NAME"
    paths:
      - .gradle/
      - build/
      - build-logic/.gradle/
      - core/**/build/
      - app/**/build/
      - feature/**/build/
      - sdk/
    policy: pull


runAndroidLintFeatureCommon:
  stage: lint
  script:
    - ./gradlew feature:feature-common:lint -x assembleDebug -x build
  artifacts:
    paths:
      - "feature/feature-common/build/reports/lint-results-debug.html"
    expire_in: 10 days
    when: always
  cache:
    key: "$CI_PROJECT_NAME"
    paths:
      - .gradle/
      - build/
      - build-logic/.gradle/
      - core/**/build/
      - app/**/build/
      - feature/**/build/
      - sdk/
    policy: pull


runAndroidLintHubs:
  stage: lint
  script:
    - ./gradlew feature:hubs:lint -x assembleDebug -x build
  artifacts:
    paths:
      - "feature/hubs/build/reports/lint-results-debug.html"
    expire_in: 10 days
    when: always
  cache:
    key: "$CI_PROJECT_NAME"
    paths:
      - .gradle/
      - build/
      - build-logic/.gradle/
      - core/**/build/
      - app/**/build/
      - feature/**/build/
      - sdk/
    policy: pull


runAndroidLintFeatureLoading:
  stage: lint
  script:
    - ./gradlew feature:loading:lint -x assembleDebug -x build
  artifacts:
    paths:
      - "feature/loading/build/reports/lint-results-debug.html"
    expire_in: 10 days
    when: always
  cache:
    key: "$CI_PROJECT_NAME"
    paths:
      - .gradle/
      - build/
      - build-logic/.gradle/
      - core/**/build/
      - app/**/build/
      - feature/**/build/
      - sdk/
    policy: pull




runAndroidLintFeatureMediaContainer:
  stage: lint
  script:
    - ./gradlew feature:media-container:lint -x assembleDebug -x build
  artifacts:
    paths:
      - "feature/media-container/build/reports/lint-results-debug.html"
    expire_in: 10 days
    when: always
  cache:
    key: "$CI_PROJECT_NAME"
    paths:
      - .gradle/
      - build/
      - build-logic/.gradle/
      - core/**/build/
      - app/**/build/
      - feature/**/build/
      - sdk/
    policy: pull


runAndroidLintFeatureProfile:
  stage: lint
  script:
    - ./gradlew feature:profile:lint -x assembleDebug -x build
  artifacts:
    paths:
      - "feature/profile/build/reports/lint-results-debug.html"
    expire_in: 10 days
    when: always
  cache:
    key: "$CI_PROJECT_NAME"
    paths:
      - .gradle/
      - build/
      - build-logic/.gradle/
      - core/**/build/
      - app/**/build/
      - feature/**/build/
      - sdk/
    policy: pull

runAndroidLintApp:
  stage: lint
  script:
    - ./gradlew app:lint -x assembleDebug -x build
  artifacts:
    paths:
      - "app/build/reports/lint-results-debug.html"
    expire_in: 10 days
    when: always
  cache:
    key: "$CI_PROJECT_NAME"
    paths:
      - .gradle/
      - build/
      - build-logic/.gradle/
      - core/**/build/
      - app/**/build/
      - feature/**/build/
      - sdk/
    policy: pull